language: python
services:
  - docker
install:
  - pip install codecov
script:
  - docker-compose up -d
  - sleep 15 && docker exec -it ng /bin/bash -c "coverage run --source='.' manage.py test"
after_success:
  - mkdir codecov && docker exec --volume=./codecov:./ ng && codecov
