language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq apt-utils build-essential python-dev liblzo2-dev liblzma-dev libsqlite3-dev python-tk tmux libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
  - pip install django
  - pip install numpy matplotlib scipy django-dbbackup psycopg2
  - pip install -r requirements-prod.txt
  - bash init_db.sh
script: python manage.py test 
